In [30]:
import numpy as np

#Одновимірний масив з першими 10 натуральними числами:
array1 = np.arange(1, 11)
print("Одновимірний масив з першими 10 натуральними числами:")
print(array1)


Одновимірний масив з першими 10 натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
#Двовимірний масив розміром 3x3 з нулями:
array2 = np.zeros((3, 3))
print("\nДвовимірний масив розміром 3x3 з нулями:")
print(array2)



Двовимірний масив розміром 3x3 з нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
#Масив розміром 5x5 з випадковими цілими числами від 1 до 10:
array3 = np.random.randint(1, 11, size=(5, 5))
print("\nМасив розміром 5x5 з випадковими цілими числами від 1 до 10:")
print(array3)


Масив розміром 5x5 з випадковими цілими числами від 1 до 10:
[[ 8 10  6 10  1]
 [ 2  1  3  3  9]
 [ 4  1  9 10  9]
 [ 6 10  5  3  6]
 [ 6  6  7  4  7]]


In [25]:
#Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:
array4 = np.random.rand(4, 4)
print("\nМасив розміром 4x4 з випадковими дійсними числами від 0 до 1:")
print(array4)


Масив розміром 4x4 з випадковими дійсними числами від 0 до 1:
[[0.21665892 0.76777838 0.56018874 0.34240971]
 [0.78534527 0.14711314 0.47709066 0.61758152]
 [0.56940002 0.76775753 0.18985396 0.9153194 ]
 [0.09354439 0.332845   0.6933361  0.57389851]]


In [26]:
#Поелементні операції з двома одновимірними масивами:
array5a = np.random.randint(1, 11, size=5)
array5b = np.random.randint(1, 11, size=5)

addition = array5a + array5b
subtraction = array5a - array5b
multiplication = array5a * array5b

print("\nПоелементні операції з двома одновимірними масивами.")
print("Оригінальні масиви:")
print("Масив 1:", array5a)
print("Масив 2:", array5b)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)



Поелементні операції з двома одновимірними масивами.
Оригінальні масиви:
Масив 1: [5 1 3 5 1]
Масив 2: [6 6 3 2 3]
Додавання: [11  7  6  7  4]
Віднімання: [-1 -5  0  3 -2]
Множення: [30  6  9 10  3]


In [27]:
#Скалярний добуток двох векторів:
vector1 = np.random.randint(1, 11, size=7)
vector2 = np.random.randint(1, 11, size=7)
dot_product = np.dot(vector1, vector2)
print("\nСкалярний добуток двох векторів.")
print("Оригінальні вектори:")
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Результат скалярного добутку:")
print(dot_product)


Скалярний добуток двох векторів.
Оригінальні вектори:
Вектор 1: [10  5  1  2  1  2 10]
Вектор 2: [ 4  1  7  8  9  4 10]
Результат скалярного добутку:
185


In [28]:
#Перемноження двох матриць розміром 2x2 та 2x3:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
result = np.matmul(matrix1, matrix2)
print("\nПеремноження двох матриць розміром 2x2 та 2x3.")
print("Оригінальні матриці:")
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Результат множення матриць:")
print(result)


Перемноження двох матриць розміром 2x2 та 2x3.
Оригінальні матриці:
Матриця 1:
[[6 7]
 [7 6]]
Матриця 2:
[[9 3 5]
 [8 9 6]]
Результат множення матриць:
[[110  81  72]
 [111  75  71]]


In [29]:
#Обернена матриця 3x3:
matrix3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix3)
print("\nОбернена матриця 3x3.")
print("Оригінальна матриця:")
print(matrix3)
print("Обернена матриця:")
print(inverse_matrix)


Обернена матриця 3x3.
Оригінальна матриця:
[[1 7 6]
 [5 9 3]
 [9 5 3]]
Обернена матриця:
[[-0.05       -0.0375      0.1375    ]
 [-0.05        0.2125     -0.1125    ]
 [ 0.23333333 -0.24166667  0.10833333]]


In [9]:
#Транспонування матриці 4x4:
matrix4 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix4)
print("\nТранспонування матриці 4x4.")
print("Оригінальна матриця:")
print(matrix4)
print("Транспонована матриця:")
print(transposed_matrix)


Транспонування матриці 4x4.
Оригінальна матриця:
[[0.08140748 0.3921822  0.79558194 0.50528454]
 [0.90978244 0.1180848  0.20513826 0.76547601]
 [0.59286045 0.70660506 0.82813457 0.79019301]
 [0.20853712 0.41613392 0.90219822 0.1541258 ]]
Транспонована матриця:
[[0.08140748 0.90978244 0.59286045 0.20853712]
 [0.3921822  0.1180848  0.70660506 0.41613392]
 [0.79558194 0.20513826 0.82813457 0.90219822]
 [0.50528454 0.76547601 0.79019301 0.1541258 ]]


In [10]:
#Перемноження матриці 3x4 на вектор розміром 4:
matrix5 = np.random.randint(1, 11, size=(3, 4))
vector3 = np.random.randint(1, 11, size=4)

result_matrix = np.matmul(matrix5, vector3)
print("\nПеремноження матриці 3x4 на вектор розміром 4.")
print("Оригінальна матриця:")
print(matrix5)
print("Оригінальний вектор:")
print(vector3)
print("Результат множення матриці на вектор:")
print(result_matrix)



Перемноження матриці 3x4 на вектор розміром 4.
Оригінальна матриця:
[[ 1  3  5  4]
 [10  6  2 10]
 [ 3 10  3  7]]
Оригінальний вектор:
[6 2 5 8]
Результат множення матриці на вектор:
[ 69 162 109]


In [11]:
#Перемноження матриці 2x3 на вектор розміром 3:
matrix6 = np.random.rand(2, 3)
vector4 = np.random.rand(3)

result_vector = np.matmul(matrix6, vector4)
print("\nПеремноження матриці 2x3 на вектор розміром 3.")
print("Оригінальна матриця:")
print(matrix6)
print("Оригінальний вектор:")
print(vector4)
print("Результат множення матриці на вектор:")
print(result_vector)



Перемноження матриці 2x3 на вектор розміром 3.
Оригінальна матриця:
[[0.24661531 0.91080018 0.59884115]
 [0.12900594 0.21463582 0.57984816]]
Оригінальний вектор:
[0.70366023 0.20102276 0.55933211]
Результат множення матриці на вектор:
[0.69157604 0.45825073]


In [12]:
#Поелементне множення двох матриць 2x2:
matrix7 = np.random.randint(1, 11, size=(2, 2))
matrix8 = np.random.randint(1, 11, size=(2, 2))

elementwise_product = np.multiply(matrix7, matrix8)
print("\nПоелементне множення двох матриць 2x2.")
print("Оригінальні матриці:")
print("Матриця 1:")
print(matrix7)
print("Матриця 2:")
print(matrix8)
print("Результат поелементного множення:")
print(elementwise_product)


Поелементне множення двох матриць 2x2.
Оригінальні матриці:
Матриця 1:
[[10  6]
 [ 7  9]]
Матриця 2:
[[ 1  9]
 [10  2]]
Результат поелементного множення:
[[10 54]
 [70 18]]


In [13]:
#Знаходження добутку двох матриць 2x2:
matrix9 = np.random.randint(1, 11, size=(2, 2))
matrix10 = np.random.randint(1, 11, size=(2, 2))
matrix_product = np.matmul(matrix9, matrix10)
print("\nЗнаходження добутку двох матриць 2x2.")
print("Оригінальні матриці:")
print("Матриця 1:")
print(matrix9)
print("Матриця 2:")
print(matrix10)
print("Результат множення матриць:")
print(matrix_product)



Знаходження добутку двох матриць 2x2.
Оригінальні матриці:
Матриця 1:
[[5 5]
 [5 3]]
Матриця 2:
[[1 4]
 [6 4]]
Результат множення матриць:
[[35 40]
 [23 32]]


In [14]:
#Знаходження суми елементів матриці 5x5:
matrix11 = np.random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix11)
print("\nЗнаходження суми елементів матриці 5x5.")
print("Оригінальна матриця:")
print(matrix11)
print("Сума елементів матриці:")
print(sum_elements)


Знаходження суми елементів матриці 5x5.
Оригінальна матриця:
[[ 3  3 44 56 47]
 [84 54 91 18 89]
 [44 70  4 44 31]
 [42 58 94 16 97]
 [54 10 20 49 67]]
Сума елементів матриці:
1189


In [15]:
#Знаходження різниці двох матриць 4x4:
matrix12 = np.random.randint(1, 11, size=(4, 4))
matrix13 = np.random.randint(1, 11, size=(4, 4))

difference_matrix = np.subtract(matrix12, matrix13)
print("\nЗнаходження різниці двох матриць 4x4.")
print("Оригінальні матриці:")
print("Матриця 1:")
print(matrix12)
print("Матриця 2:")
print(matrix13)
print("Різниця матриць:")
print(difference_matrix)


Знаходження різниці двох матриць 4x4.
Оригінальні матриці:
Матриця 1:
[[ 6  2  3 10]
 [ 3  1  2  4]
 [ 8  5  9  1]
 [ 6  6  7  1]]
Матриця 2:
[[ 3  8  6  7]
 [ 3  8  9  4]
 [ 8 10  7  6]
 [ 5  9  4  3]]
Різниця матриць:
[[ 3 -6 -3  3]
 [ 0 -7 -7  0]
 [ 0 -5  2 -5]
 [ 1 -3  3 -2]]


In [16]:
#Знаходження вектор-стовпчика із сум елементів кожного рядка матриці 3x3:
matrix14 = np.random.rand(3, 3)
row_sums = np.sum(matrix14, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("\nЗнаходження вектор-стовпчика із сум елементів кожного рядка матриці 3x3.")
print("Оригінальна матриця:")
print(matrix14)
print("Вектор-стовпчик з сумами рядків:")
print(column_vector)


Знаходження вектор-стовпчика із сум елементів кожного рядка матриці 3x3.
Оригінальна матриця:
[[0.46969094 0.02223009 0.57511152]
 [0.47709114 0.84553098 0.32949178]
 [0.49717653 0.60793562 0.7866986 ]]
Вектор-стовпчик з сумами рядків:
[[1.06703255]
 [1.6521139 ]
 [1.89181075]]


In [17]:
#Створення матриці з квадратами чисел у матриці 3x4:
matrix15 = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix15)
print("\nСтворення матриці з квадратами чисел у матриці 3x4.")
print("Оригінальна матриця:")
print(matrix15)
print("Матриця з квадратами чисел:")
print(squared_matrix)


Створення матриці з квадратами чисел у матриці 3x4.
Оригінальна матриця:
[[3 6 2 1]
 [1 2 2 3]
 [4 1 1 6]]
Матриця з квадратами чисел:
[[ 9 36  4  1]
 [ 1  4  4  9]
 [16  1  1 36]]


In [21]:
#Створення вектора з квадратними коренями чисел у векторі розміром 4:
vector5 = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector5)
print("\nСтворення вектора з квадратними коренями чисел у векторі розміром 4.")
print("Оригінальний вектор:")
print(vector5)
print("Вектор з квадратними коренями чисел:")
print(sqrt_vector)


Створення вектора з квадратними коренями чисел у векторі розміром 4.
Оригінальний вектор:
[ 5 50  3 39]
Вектор з квадратними коренями чисел:
[2.23606798 7.07106781 1.73205081 6.244998  ]
